/--- Day 16: Aunt Sue ---

s:{[x] (!)."ni"$+2^@[" "\",:"_ x;2 3 4 5 6 7]}'0:"input/16.txt"
t:(+`sue!1+!#s),'{[x;y] (x!(#x)#-1),y }[c:?,/!'s;]'s

first first select sue from select from(select from(select from(select from(select from(select from(select from (select from(select from(select from t where children in -1 3) where cats in -1 7) where samoyeds in -1 2) where pomeranians in -1 3) where akitas in -1 0) where vizslas in -1 0) where goldfish in -1 5) where trees in -1 3) where cars in -1 2) where perfumes in -1 1

first first select sue from select from(select from(select from(select from(select from(select from(select from(select from(select from(select from t where children in -1 3) where (cats > 7)|cats=-1) where samoyeds in -1 2) where (pomeranians <3)|pomeranians=-1) where akitas in -1 0) where vizslas in -1 0) where (goldfish < 5)|goldfish = -1) where (trees>3)|trees=-1) where cars in -1 2) where perfumes in -1 1
